# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MasterUser',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=18)),
                ('Token', models.CharField(max_length=18)),
                ('FirstName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('BirthDate', models.DateTimeField(auto_now=True)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('HomeAddress', models.TextField(blank=True)),
                ('AboutMe', models.TextField(blank=True)),
                ('ProfilePicture', models.CharField(max_length=500)),
                ('CalendarID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CreatedOn', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('Location', models.TextField(blank=True)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('OtherRelated', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('MemoryLink', models.CharField(max_length=500)),
                ('Picture', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPeople',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('RelationshipDescription', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SubUser',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=18)),
                ('Email', models.EmailField(max_length=254)),
                ('CreatedDate', models.DateTimeField(auto_now=True)),
                ('BirthDate', models.DateTimeField(auto_now=True)),
                ('FirstName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('MemoryLink', models.CharField(max_length=500)),
                ('Video', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='masteruser',
            name='SubUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.SubUser'),
        ),
    ]
