# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(max_length=18)),
                ('CreatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedOn', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('Location', models.TextField(blank=True)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemoryLink', models.CharField(max_length=500)),
                ('Picture', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('RelationshipDescription', models.CharField(max_length=500)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='SubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDate', models.DateTimeField(auto_now=True)),
                ('Pictures', models.ManyToManyField(to='mainApp.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=18)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=18)),
                ('FirstName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('BirthDate', models.DateTimeField(auto_now=True)),
                ('ProfilePicture', models.CharField(max_length=500)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('HomeAddress', models.TextField(blank=True)),
                ('AboutMe', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemoryLink', models.CharField(max_length=500)),
                ('Video', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='subuser',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User'),
        ),
        migrations.AddField(
            model_name='subuser',
            name='Videos',
            field=models.ManyToManyField(to='mainApp.Video'),
        ),
        migrations.AddField(
            model_name='memory',
            name='OtherRelated',
            field=models.ManyToManyField(to='mainApp.User'),
        ),
        migrations.AddField(
            model_name='memory',
            name='SubUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.SubUser'),
        ),
        migrations.AddField(
            model_name='client',
            name='SubUser',
            field=models.ManyToManyField(to='mainApp.SubUser'),
        ),
        migrations.AddField(
            model_name='client',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Client'),
        ),
    ]
