# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SubUser',
        ),
    ]
