# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Token',
            new_name='Reference_ID',
        ),
        migrations.AlterField(
            model_name='memory',
            name='Title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='ProfilePicture',
            field=models.ImageField(upload_to='Profile_Picures'),
        ),
    ]
