# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 23:32
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20160424_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ProfilePicture',
            field=stdimage.models.StdImageField(blank=True, upload_to='Profile_Pictures'),
        ),
    ]
