# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20160508_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialperson',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='specialperson',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='specialperson',
            name='RelationshipDescription',
        ),
        migrations.AddField(
            model_name='specialperson',
            name='SubUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.SubUser'),
            preserve_default=False,
        ),
    ]
